- ignore:
    name: "Replace case with maybe"
- ignore:
    name: "Reduce duplication"
- ignore:
    name: "Use newtype instead of data"
- ignore:
    name: "Use ++"
- ignore:
    name: "Use tuple-section"
