snapshot: lts-14.23
packages:
- intray-api
- intray-api-gen
- intray-cli
- intray-client
- intray-data
- intray-data-gen
- intray-server
- intray-server-gen
- intray-web-server
- stripeapi
extra-deps:
- envparse-0.4.1@sha256:989902e6368532548f61de1fa245ad2b39176cddd8743b20071af519a709ce30,2842
- servant-auth-client-0.4.0.0@sha256:68879b7f44d87f73ef68c7bb21006167f5623c4cd6a2a3fce4d5ea3959a8c730,3426
- servant-flatten-0.2@sha256:276896f7c5cdec5b8f8493f6205fded0cc602d050b58fdb09a6d7c85c3bb0837,1234

# https://github.com/vincenthz/hs-tls/issues/421
# see also nix/overlay.nix.
- github: ocheron/hs-tls
  commit: 8d2201a7e73f826633a9537b98a24096252950cc
  subdirs:
    - core
    - debug
    - session

- github: NorfairKing/yesod-static-remote
  commit: 22c0a92c1d62f1b8d432003844ef0636a9131b08
- github: NorfairKing/stripe
  commit: 7ced8cef1e932d3fb222dfb3c79c25595cdc82ab
  subdirs:
    - stripe-core
    - stripe-haskell
    - stripe-http-client
    - stripe-http-streams
- github: NorfairKing/mergeless
  commit: 079c9ba60aa87d0a1f2eb344c9fba94c97050e61
  subdirs:
    - mergeless
    - genvalidity-mergeless
    - mergeless-persistent
- github: NorfairKing/validity
  commit: 95ec39a2535b9c83b1163015fd2ca28317debf42
  subdirs:
  - genvalidity
  - genvalidity-aeson
  - genvalidity-bytestring
  - genvalidity-containers
  - genvalidity-criterion
  - genvalidity-hspec
  - genvalidity-hspec-aeson
  - genvalidity-hspec-binary
  - genvalidity-hspec-cereal
  - genvalidity-hspec-hashable
  - genvalidity-hspec-optics
  - genvalidity-hspec-persistent
  - genvalidity-path
  - genvalidity-persistent
  - genvalidity-property
  - genvalidity-scientific
  - genvalidity-text
  - genvalidity-time
  - genvalidity-unordered-containers
  - genvalidity-uuid
  - genvalidity-vector
  - validity
  - validity-aeson
  - validity-bytestring
  - validity-containers
  - validity-path
  - validity-persistent
  - validity-primitive
  - validity-scientific
  - validity-text
  - validity-time
  - validity-unordered-containers
  - validity-uuid
  - validity-vector
- github: NorfairKing/typed-uuid
  commit: dbc8fd4b56b78b1f9cf00bc2890d43dc19b97c5c
  subdirs:
    - typed-uuid
    - genvalidity-typed-uuid
- github: NorfairKing/pretty-relative-time
  commit: fc62907b36f6f7348d6ae0e97aceb4d41039d57b
- github: NorfairKing/looper
  commit: 464f47c757b956019d5723590a09f85662513b24
- github: NorfairKing/yamlparse-applicative
  commit: 3775e2a9152214fdfcbc04032ee3eb28349b5abd
  subdirs:
    - yamlparse-applicative

nix:
  path: [ "nixpkgs=https://github.com/NixOS/nixpkgs/archive/323fe92057bb38475a446ff5e18d3b388c2e4403.tar.gz" ]
  add-gc-roots: true
  pure: true
  packages:
  - zlib
  - unzip
  - haskellPackages.autoexporter
  - procps
